pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                sh 'pytohn -m pip install virtualenv'
                sh 'virtualenv env'
                sh 'source ./env/bin/activate'
                sh 'python -m pip install -r requirements.txt' 
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                sh 'pytest'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}