pipeline {
    agent {
        docker 
        {
            image 'python:3.9.2'
        }
    }
    stages {
        stage('Build') {
            
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python -m pip install --no-cache-dir --user -r requirements.txt' 
                }
            }
        }
        stage('Unit Test') {
            
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    
                    
                    sh 'python -m unittest -v test.py'
                }
            }

        }
        stage('Measure the slowlest Unit Tests Execution Time') {
            
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    
                    sh 'python test.py'
                }
            }

        }
    }
}