pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                sh 'ls'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                sh 'py.test'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}